# encoding:utf8
# try-finally 语句无论是否发生异常都将执行最后的代码。

try:
    print('这是try语句下的内容。')
finally:
    print('这是finally语句下的内容。')
